name: MacOS_Pester

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: Install-Module -Name 'Pester','PSSQLite' -Force -SkipPublisherCheck
      shell: pwsh
    - name: Run tests
      run: Invoke-Pester -Path './tests' -ErrorAction Stop
      shell: pwsh