name: Pester Tests

on:
  pull_request:
    branches:
      - main
    paths:
      - "UofIDMI/**"

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: Install-Module -Name 'PSSQLite' -Force -SkipPublisherCheck -RequiredVersion '1.1'; Install-Module -Name 'Pester' -Force -SkipPublisherCheck
      shell: pwsh
    - name: Run tests
      run: Invoke-Pester -Path './tests/' -CI
      shell: pwsh
