name: Pester Tests

on: [pull_request]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: Install-Module -Name 'PSDepend' -Force -SkipPublisherCheck; Invoke-PSDepend -Path '.github\workflows\requirements.psd1' -Force
      shell: pwsh
    - name: Run tests
      run: Invoke-Pester -Path './tests' -EnableExit -ErrorAction Stop
      shell: pwsh