name: Pester Tests

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: Install-Module -Name 'Pester','PSSQLite' -Force -SkipPublisherCheck
      shell: pwsh
    - name: Run tests
      run: Invoke-Pester -Path './tests' -ErrorAction Stop
      shell: pwsh