name: ScriptAnalyzer

on:
  pull_request:
    branches:
      - main
    paths:
      - "UofIDMI/**"

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: Install-Module -Name 'PSScriptAnalyzer' -Force -SkipPublisherCheck
      shell: pwsh
    - name: ScriptAnalyzer
      run: Invoke-ScriptAnalyzer -Path '.\UofIDMI\' -Recurse -EnableExit
      shell: pwsh
