name: ScriptAnalyzer

on: [pull_request]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: Install-Module -Name 'PSScriptAnalyzer' -Force -SkipPublisherCheck
      shell: pwsh
    - name: Run tests
      run: Invoke-ScriptAnalyzer -Path '.\UofIDMI\' -Recurse -EnableExit
      shell: pwsh